[project]
name = "ans-2-snowflake-ml"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "snowflake-ml-python>=1.9.0",
    "snowflake-snowpark-python>=1.33.0",
]
