[project]
name = "ans-1-to-pandas"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pandas>=1.5.3",
    "pyarrow>=20.0.0",
    "scikit-learn>=1.7.0",
    "snowflake-snowpark-python>=1.33.0",
]
